using System;

namespace JPB.Console.Helper.Grid.NetCore.Grid
{
	public class ConsoleGridColumn
	{
		internal bool AutoGenerated { get; set; }

		public AlignedProperty AlignedProperty { get; set; }

		public string Name { get; set; }
		public int MaxContentSize { get; set; }

		public int MaxSize
		{
			get
			{
				var val = Name.Length > MaxContentSize ? Name.Length : MaxContentSize;
				return val;
			}
		}

		public Func<object, object> GetValue { get; set; }
	}

	public class ConsoleGridColumn<T> : ConsoleGridColumn
	{
		public new Func<T, object> GetValue
		{
			get { return (arg) => base.GetValue(arg); }
			set { base.GetValue = o => value((T)o); }
		}
	}
}